server:
  port: 8003

spring:
  application:
    name: service-provider

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/
    instance:
      prefer-ip-address: true

info:
  app.name: ${spring.application.name}
  company.name: helloworld
  build.artifactId: @project.artifactId@
  build.version: @project.version@
