server:
  port: 7002

eureka:
  instance:
    appname: eureka-server
    #eureka服务端的实例名称
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}:@project.version@
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #单机设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #Eureka高复用时设置其他的Eureka之间通信
      #defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/
  #server:
    #enable-self-preservation: false   #Eureka服务端关闭心跳连接测试

#/actuator/info
info:
  app:
    name: eureka-server
  company:
    name: helloworld
  build:
    artifactId: @project.artifactId@
    version: @project.version@