server:
  port: 8007

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: /export/workspace/hello-springcloud/config-server/conf

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7002/eureka
  healthcheck:
    enabled: true
  instance:
    prefer-ip-address: true

info:
  app.name: ${spring.application.name}
  company.name: helloworld
  build.artifactId: @project.artifactId@
  build.version: @project.version@