server:
  port: 8003

spring:
  application:
    name: ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7002/eureka
  healthcheck:
    enabled: true
  instance:
    prefer-ip-address: true

info:
  app.name: ribbon
  company.name: helloworld
  build.artifactId: @project.artifactId@
  build.version: @project.version@